export const ACTIVATE_AIMING_CARD = "ACTIVATE_AIMING_CARD";
export const ADD_ONE_CARD = "ADD_ONE_CARD";
export const ADD_MANY_CARDS = "ADD_MANY_CARDS";
export const DELETE_ALL_CARDS = "DELETE_ALL_CARDS";
export const DELETE_ONE_CARDS = "DELETE_ONE_CARDS"
export const SELECT_CARD = "SELECT_CARD";
export const UNSELECT_CARD = "UNSELECT_CARD";
