// Battle
export const ACTIVATE_AIMING_CARD = "ACTIVATE_AIMING_CARD";
export const ADD_ONE_CARD = "ADD_ONE_CARD";
export const ADD_MANY_CARDS = "ADD_MANY_CARDS";
export const DELETE_ALL_CARDS = "DELETE_ALL_CARDS";
export const DELETE_ONE_CARDS = "DELETE_ONE_CARDS";
export const SELECT_CARD = "SELECT_CARD";
export const UNSELECT_CARD = "UNSELECT_CARD";
export const SET_AIMING_CARD = "SET_AIMING_CARD";
export const SET_HOVERED_CARD = "SET_HOVERED_CARD";
export const CLEAR_HOVERED_CARD = "CLEAR_HOVERED_CARD";

export const ADD_CARDS_TO_HAND = "ADD_CARDS_TO_HAND";
export const DELETE_CARDS_FROM_HAND = "DELETE_CARDS_FROM_HAND";
export const ADD_CARDS_TO_DRAW_PILE = "ADD_CARDS_TO_DRAW_PILE";
export const DELETE_CARDS_FROM_DRAW_PILE = "DELETE_CARDS_FROM_DRAW_PILE";
export const ADD_CARDS_TO_DISCARD_PILE = "ADD_CARDS_TO_DISCARD_PILE";
export const DELETE_CARDS_FROM_DISCARD_PILE = "DELETE_CARDS_FROM_DISCARD_PILE";

export const TOGGLE_DRAW_PILE = "TOGGLE_DRAW_PILE";
export const TOGGLE_DISCARD_PILE = "TOGGLE_DISCARD_PILE";

// animation

export const QUEUE_ANIMATION = "QUEUE_ANIMATION";
export const START_PLAYING_ANIMATION = "START_PLAYING_ANIMATION";
export const FINISH_PLAYING_ANIMATION = "FINISH_PLAYING_ANIMATION";
export const RUN_NEXT_ANIMATION = "RUN_NEXT_ANIMATION";
export const DEQUEUE_ANIMATION = "DEQUEUE_ANIMATION";

export const REMOVE_SLIDE_IN_ANIMATION = "REMOVE_SLIDE_IN_ANIMATION";



// Player
export const ADD_ONE_CARD_TO_DECK = "ADD_ONE_CARD_TO_DECK";

// Setting
export const TOGGLE_DECK_OF_CARDS = "TOGGLE_DECK_OF_CARDS";